/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

import { Route as rootRouteImport } from './routes/__root'
import { Route as AliasesRouteImport } from './routes/aliases'
import { Route as AliasIdRouteImport } from './routes/$aliasId'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthSettingsRouteImport } from './routes/auth/settings'
import { Route as AuthRegisterRouteImport } from './routes/auth/register'
import { Route as AuthLoginRouteImport } from './routes/auth/login'

const AuthErrorLazyRouteImport = createFileRoute('/auth/error')()

const AliasesRoute = AliasesRouteImport.update({
  id: '/aliases',
  path: '/aliases',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/aliases.lazy').then((d) => d.Route))
const AliasIdRoute = AliasIdRouteImport.update({
  id: '/$aliasId',
  path: '/$aliasId',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/$aliasId.lazy').then((d) => d.Route))
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthErrorLazyRoute = AuthErrorLazyRouteImport.update({
  id: '/auth/error',
  path: '/auth/error',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/error.lazy').then((d) => d.Route))
const AuthSettingsRoute = AuthSettingsRouteImport.update({
  id: '/auth/settings',
  path: '/auth/settings',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/settings.lazy').then((d) => d.Route))
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/register.lazy').then((d) => d.Route))
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/auth/login.lazy').then((d) => d.Route))

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$aliasId': typeof AliasIdRoute
  '/aliases': typeof AliasesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/settings': typeof AuthSettingsRoute
  '/auth/error': typeof AuthErrorLazyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$aliasId': typeof AliasIdRoute
  '/aliases': typeof AliasesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/settings': typeof AuthSettingsRoute
  '/auth/error': typeof AuthErrorLazyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$aliasId': typeof AliasIdRoute
  '/aliases': typeof AliasesRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/settings': typeof AuthSettingsRoute
  '/auth/error': typeof AuthErrorLazyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$aliasId'
    | '/aliases'
    | '/auth/login'
    | '/auth/register'
    | '/auth/settings'
    | '/auth/error'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$aliasId'
    | '/aliases'
    | '/auth/login'
    | '/auth/register'
    | '/auth/settings'
    | '/auth/error'
  id:
    | '__root__'
    | '/'
    | '/$aliasId'
    | '/aliases'
    | '/auth/login'
    | '/auth/register'
    | '/auth/settings'
    | '/auth/error'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AliasIdRoute: typeof AliasIdRoute
  AliasesRoute: typeof AliasesRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthErrorLazyRoute: typeof AuthErrorLazyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/aliases': {
      id: '/aliases'
      path: '/aliases'
      fullPath: '/aliases'
      preLoaderRoute: typeof AliasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$aliasId': {
      id: '/$aliasId'
      path: '/$aliasId'
      fullPath: '/$aliasId'
      preLoaderRoute: typeof AliasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/error': {
      id: '/auth/error'
      path: '/auth/error'
      fullPath: '/auth/error'
      preLoaderRoute: typeof AuthErrorLazyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/settings': {
      id: '/auth/settings'
      path: '/auth/settings'
      fullPath: '/auth/settings'
      preLoaderRoute: typeof AuthSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AliasIdRoute: AliasIdRoute,
  AliasesRoute: AliasesRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthErrorLazyRoute: AuthErrorLazyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
